# Generated by Django 4.2 on 2023-05-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
