# Generated by Django 4.2 on 2023-05-02 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_appointment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='likes',
        ),
        migrations.AddField(
            model_name='appointment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
