# Generated by Django 4.2 on 2023-05-02 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_appointment_likes_appointment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
