# Generated by Django 4.2 on 2023-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appointment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='miles',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
