# Generated by Django 4.2 on 2023-05-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='likes',
        ),
    ]
