export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS";

